import { Client } from '@/hooks/use-clients';
import { Session } from '@/hooks/use-sessions';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { formatCurrency } from "react-native-format-currency";

interface InvoiceData {
    client: Client;
    sessions: Session[];
    currency: string;
    invoiceNumber: string;
    startDate: Date;
    endDate: Date;
}

export const generateInvoice = async ({ client, sessions, currency, invoiceNumber, startDate, endDate }: InvoiceData) => {
    const totalAmount = sessions.reduce((acc, s) => {
        const hours = s.elapsedTime / (1000 * 60 * 60);
        const rate = parseFloat(s.rate || '0');
        return acc + (hours * rate);
    }, 0);

    const [formattedTotal] = formatCurrency({ amount: Number(totalAmount.toFixed(2)), code: currency });

    const rows = sessions.map(s => {
        const date = new Date(s.startTime).toLocaleDateString();
        const duration = (s.elapsedTime / (1000 * 60 * 60)).toFixed(2) + ' hrs';
        const rate = s.rate;
        const amount = ((s.elapsedTime / (1000 * 60 * 60)) * parseFloat(s.rate || '0')).toFixed(2);
        
        return `
            <tr>
                <td>${date}</td>
                <td>Development / Design</td>
                <td>${duration}</td>
                <td>${rate}</td>
                <td>${amount}</td>
            </tr>
        `;
    }).join('');

    const html = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
                .header { display: flex; justify-content: space-between; margin-bottom: 50px; }
                .title { font-size: 45px; line-height: 45px; color: #333; font-weight: bold; }
                .meta { text-align: right; }
                
                .client-box { margin-bottom: 40px; padding: 20px; background: #f9f9f9; border-left: 6px solid ${client.color || '#333'}; }
                
                table { width: 100%; line-height: inherit; text-align: left; border-collapse: collapse; }
                table td { padding: 10px; vertical-align: top; }
                table tr.heading td { background: #eee; border-bottom: 1px solid #ddd; font-weight: bold; text-transform: uppercase; font-size: 12px; }
                table tr.item td { border-bottom: 1px solid #eee; }
                table tr.total td:nth-child(5) { border-top: 2px solid #333; font-weight: bold; font-size: 18px; }
                
                .footer { margin-top: 50px; text-align: center; color: #999; font-size: 12px; }
            </style>
        </head>
        <body>
            <div>
                <div class="header">
                    <div>
                        <div class="title">INVOICE</div>
                        <div>#${invoiceNumber}</div>
                    </div>
                    <div class="meta">
                        <div><strong>Created:</strong> ${new Date().toLocaleDateString()}</div>
                        <div><strong>Period:</strong> ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}</div>
                    </div>
                </div>

                <div class="client-box">
                    <strong>Bill To:</strong><br>
                    ${client.name}
                </div>

                <table>
                    <tr class="heading">
                        <td>Date</td>
                        <td>Description</td>
                        <td>Hours</td>
                        <td>Rate</td>
                        <td>Total</td>
                    </tr>
                    ${rows}
                    <tr class="total">
                        <td></td><td></td><td></td>
                        <td>Total:</td>
                        <td>${formattedTotal}</td>
                    </tr>
                </table>

                <div class="footer">
                    Generated by ClariRate
                </div>
            </div>
        </body>
        </html>
    `;

    try {
        const { uri } = await Print.printToFileAsync({ html });
        console.log('File has been saved to:', uri);
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('PDF Generation failed', error);
    }
}